"""add_is_public_to_cores_and_connects

Revision ID: 0f2238754185
Revises: eb905c1aae49
Create Date: 2026-04-28 16:16:57.498270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f2238754185'
down_revision: Union[str, None] = 'eb905c1aae49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connects', sa.Column('is_public', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('cores', sa.Column('is_public', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cores', 'is_public')
    op.drop_column('connects', 'is_public')
    # ### end Alembic commands ###
