"""legacy_created_by_name on core and connect data items

Revision ID: 424eda8a6ad5
Revises: 3b6c4430eeda
Create Date: 2026-04-30 11:23:28.469003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '424eda8a6ad5'
down_revision: Union[str, None] = '3b6c4430eeda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connect_data_items', sa.Column('legacy_created_by_name', sa.String(length=255), nullable=True))
    op.add_column('core_data_items', sa.Column('legacy_created_by_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('core_data_items', 'legacy_created_by_name')
    op.drop_column('connect_data_items', 'legacy_created_by_name')
    # ### end Alembic commands ###
