"""initial schema

Revision ID: 5265f3587475
Revises: 
Create Date: 2026-04-28 10:45:49.733892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5265f3587475'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='statusenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=200), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('entity_name', sa.String(length=500), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('performed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('connects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='statusenum'), nullable=False),
    sa.Column('schema_finalised', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('assigned_stocker_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_stocker_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('folders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('language_registry',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('language_name_en', sa.String(length=100), nullable=False),
    sa.Column('language_name_native', sa.String(length=100), nullable=False),
    sa.Column('script', sa.String(length=100), nullable=False),
    sa.Column('direction', sa.Enum('LTR', 'RTL', name='textdirection'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='statusenum'), nullable=False),
    sa.Column('added_by', sa.String(length=36), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('language_code')
    )
    op.create_table('product_registry',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('sync_endpoint_url', sa.Text(), nullable=True),
    sa.Column('sync_api_key_secret_name', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='statusenum'), nullable=False),
    sa.Column('added_by', sa.String(length=36), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('relationship_type_registry',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('example', sa.Text(), nullable=True),
    sa.Column('added_by', sa.String(length=36), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label')
    )
    op.create_table('user_roles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'DESIGNER', 'STOCKER', 'REVIEWER', name='userrole'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='statusenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role')
    )
    op.create_table('connect_data_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('connect_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='statusenum'), nullable=False),
    sa.Column('legacy_connect_data_id', sa.String(length=50), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['connect_id'], ['connects.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('connect_product_tags',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('connect_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['connect_id'], ['connects.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product_registry.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connect_id', 'product_id')
    )
    op.create_table('cores',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('folder_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('core_type', sa.Enum('TEXT', 'MEDIA', name='coretype'), nullable=False),
    sa.Column('content_type', sa.Enum('IMAGE', 'VIDEO', 'AUDIO', 'DOCUMENT', name='contenttype'), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('language_mode', sa.Enum('TRANSLATION', 'TRANSLITERATION', name='languagemode'), nullable=True),
    sa.Column('legacy_core_id', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='statusenum'), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('assigned_stocker_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_stocker_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('product_sync_state',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('last_successful_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_mode', sa.Enum('FULL', 'INCREMENTAL', name='syncmode'), nullable=True),
    sa.Column('last_sync_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product_registry.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_table('sync_change_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.Enum('CORE', 'CONNECT', 'CORE_DATA_ITEM', 'CONNECT_DATA_ITEM', 'TRANSLATION', name='entitytype'), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('change_type', sa.Enum('ADDED', 'UPDATED', 'INACTIVATED', 'REACTIVATED', 'TRANSLATION_UPDATED', name='changetype'), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('included_in_sync_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product_registry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sync_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('sync_mode', sa.Enum('FULL', 'INCREMENTAL', name='syncmode'), nullable=False),
    sa.Column('initiated_by', sa.String(length=36), nullable=True),
    sa.Column('initiated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('DISPATCHED', 'COMPLETED', 'PARTIAL', 'FAILED', name='syncstatus'), nullable=False),
    sa.Column('total_items', sa.Integer(), nullable=True),
    sa.Column('items_inserted', sa.Integer(), nullable=True),
    sa.Column('items_updated', sa.Integer(), nullable=True),
    sa.Column('items_failed', sa.Integer(), nullable=True),
    sa.Column('product_response', sa.JSON(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['initiated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product_registry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('connect_schema_positions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('connect_id', sa.String(length=36), nullable=False),
    sa.Column('position_number', sa.Integer(), nullable=False),
    sa.Column('core_id', sa.String(length=36), nullable=False),
    sa.Column('relationship_type_to_next', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['connect_id'], ['connects.id'], ),
    sa.ForeignKeyConstraint(['core_id'], ['cores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connect_id', 'position_number')
    )
    op.create_table('core_data_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('core_id', sa.String(length=36), nullable=False),
    sa.Column('english_value', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='statusenum'), nullable=False),
    sa.Column('legacy_item_id', sa.String(length=50), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['core_id'], ['cores.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('core_language_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('core_id', sa.String(length=36), nullable=False),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['core_id'], ['cores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('core_id', 'language_code')
    )
    op.create_table('core_product_tags',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('core_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['core_id'], ['cores.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product_registry.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('core_id', 'product_id')
    )
    op.create_table('connect_data_positions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('connect_data_item_id', sa.String(length=36), nullable=False),
    sa.Column('position_number', sa.Integer(), nullable=False),
    sa.Column('core_data_item_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['connect_data_item_id'], ['connect_data_items.id'], ),
    sa.ForeignKeyConstraint(['core_data_item_id'], ['core_data_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connect_data_item_id', 'position_number')
    )
    op.create_table('core_data_translations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('translated_value', sa.Text(), nullable=False),
    sa.Column('validation_status', sa.Enum('MACHINE_GENERATED', 'EXPERT_VALIDATED', name='validationstatus'), nullable=False),
    sa.Column('validated_by', sa.String(length=36), nullable=True),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['core_data_items.id'], ),
    sa.ForeignKeyConstraint(['validated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'language_code')
    )
    op.create_table('media_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('s3_url', sa.Text(), nullable=False),
    sa.Column('content_type', sa.Enum('IMAGE', 'VIDEO', 'AUDIO', 'DOCUMENT', name='contenttype'), nullable=True),
    sa.Column('language_code', sa.String(length=10), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['core_data_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id')
    )
    op.create_table('similarity_pairs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('item_id_a', sa.String(length=36), nullable=False),
    sa.Column('item_id_b', sa.String(length=36), nullable=False),
    sa.Column('similarity_score', sa.DECIMAL(precision=5, scale=4), nullable=False),
    sa.Column('similarity_reason', sa.Enum('EXACT_DUPLICATE', 'FORMAT_DIFFERENCE', 'SPELLING_ERROR', 'REARRANGED_WORDS', 'MISSING_WORDS', 'ABBREVIATION', name='similarityreason'), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'KEEP_BOTH', 'REMOVE_ONE', 'MERGED', 'IGNORED', name='similaritystatus'), nullable=False),
    sa.Column('reviewed_by', sa.String(length=36), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('merged_canonical_value', sa.Text(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id_a'], ['core_data_items.id'], ),
    sa.ForeignKeyConstraint(['item_id_b'], ['core_data_items.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id_a', 'item_id_b')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('similarity_pairs')
    op.drop_table('media_items')
    op.drop_table('core_data_translations')
    op.drop_table('connect_data_positions')
    op.drop_table('core_product_tags')
    op.drop_table('core_language_configs')
    op.drop_table('core_data_items')
    op.drop_table('connect_schema_positions')
    op.drop_table('sync_history')
    op.drop_table('sync_change_log')
    op.drop_table('product_sync_state')
    op.drop_table('cores')
    op.drop_table('connect_product_tags')
    op.drop_table('connect_data_items')
    op.drop_table('user_roles')
    op.drop_table('relationship_type_registry')
    op.drop_table('product_registry')
    op.drop_table('language_registry')
    op.drop_table('folders')
    op.drop_table('connects')
    op.drop_table('audit_log')
    op.drop_table('users')
    # ### end Alembic commands ###
