"""add_entity_type_label_to_product_tags

Revision ID: eb905c1aae49
Revises: 5265f3587475
Create Date: 2026-04-28 15:57:50.043486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb905c1aae49'
down_revision: Union[str, None] = '5265f3587475'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connect_product_tags', sa.Column('entity_type_label', sa.String(length=100), nullable=True))
    op.add_column('core_product_tags', sa.Column('entity_type_label', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('core_product_tags', 'entity_type_label')
    op.drop_column('connect_product_tags', 'entity_type_label')
    # ### end Alembic commands ###
